runtime: nodejs20
env: standard

handlers:
- url: /.*
  script: auto
  secure: always

env_variables:
  NODE_ENV: 'production'
  PORT: '8080'

instance_class: F2
automatic_scaling:
  min_idle_instances: 1
  max_idle_instances: 2
  min_pending_latency: 30ms
  max_pending_latency: 60ms
  # min_running_instances: 1
  # max_running_instances: 10
